language: r
cache: packages
os:
  - linux
  - osx

addons:
  apt:
    sources: [ 'ubuntu-toolchain-r-test']
    packages: ['libstdc++6']

notifications:
  email: false

before_install:
  - mkdir -p ~/Downloads

  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then curl -L https://julialang-s3.julialang.org/bin/linux/x64/0.6/julia-0.6.2-linux-x86_64.tar.gz -o "$HOME/Downloads/julia.tar.gz"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then tar xzf "$HOME/Downloads/julia.tar.gz" -C "$HOME/Downloads"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cp -r "$(find "$HOME/Downloads" -maxdepth 2 -name "julia*" -type d | head -n 1)" "$HOME/julia"; fi

  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then curl -L https://julialang-s3.julialang.org/bin/mac/x64/0.6/julia-0.6.2-mac64.dmg -o "$HOME/Downloads/julia.dmg"; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then hdiutil attach ~/Downloads/julia.dmg; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then cp -r /Volumes/Julia*/Julia*/Contents/Resources/julia $HOME/julia; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then hdiutil detach -force /Volumes/Julia*; fi

  - rm -rf ~/Downloads/julia*
  - export PATH="$HOME/julia/bin:$PATH"
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export R_LD_LIBRARY_PATH="$(R RHOME)/lib:$HOME/julia/lib/julia"; fi

install:
  - R -e "install.packages(\"devtools\", repos=\"http://cran.rstudio.com/\")"
  - R -e 'devtools::install_deps(dep = T)'
  - R -e "install.packages(\"remotes\", repos=\"http://cran.rstudio.com/\")"
  - R -e "remotes::install_github(\"Non-Contradiction/JuliaCall\")"
